//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SceneCrm.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.CourseAttendances = new HashSet<CourseAttendance>();
            this.CourseVolunteers = new HashSet<CourseVolunteer>();
        }
    
        public int CourseId { get; set; }
        public string CourseTypeCode { get; set; }
        public Nullable<int> TermId { get; set; }
        public Nullable<int> Year { get; set; }
    
        public virtual CourseType CourseType { get; set; }
        public virtual Term Term { get; set; }
        public virtual ICollection<CourseAttendance> CourseAttendances { get; set; }
        public virtual ICollection<CourseVolunteer> CourseVolunteers { get; set; }
    }
}
