//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SceneCrm.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseType
    {
        public CourseType()
        {
            this.Courses = new HashSet<Course>();
        }
    
        public string CourseTypeCode { get; set; }
        public string CourseTypeName { get; set; }
    
        public virtual ICollection<Course> Courses { get; set; }
    }
}
