//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SceneCrm.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseAttendance
    {
        public int StudentId { get; set; }
        public int CourseId { get; set; }
        public Nullable<bool> Completed { get; set; }
        public Nullable<int> PlayId { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Student Student { get; set; }
        public virtual Play Play { get; set; }
    }
}
