//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SceneCrm.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public Job()
        {
            this.CourseVolunteers = new HashSet<CourseVolunteer>();
            this.PlayVolunteers = new HashSet<PlayVolunteer>();
            this.ProductionVolunteers = new HashSet<ProductionVolunteer>();
            this.Volunteers = new HashSet<Volunteer>();
        }
    
        public int JobId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<CourseVolunteer> CourseVolunteers { get; set; }
        public virtual ICollection<PlayVolunteer> PlayVolunteers { get; set; }
        public virtual ICollection<ProductionVolunteer> ProductionVolunteers { get; set; }
        public virtual ICollection<Volunteer> Volunteers { get; set; }
    }
}
