//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SceneCrm.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Performance
    {
        public int PerformanceId { get; set; }
        public Nullable<int> ProductionId { get; set; }
        public Nullable<System.DateTime> PerformanceDateTime { get; set; }
        public string EventBriteId { get; set; }
    
        public virtual Production Production { get; set; }
    }
}
