//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SceneCrm.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayVolunteer
    {
        public int PlayId { get; set; }
        public int VolunteerId { get; set; }
        public int JobId { get; set; }
        public string Notes { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual Play Play { get; set; }
        public virtual Volunteer Volunteer { get; set; }
    }
}
