//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SceneCrm.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Play
    {
        public Play()
        {
            this.PlayVolunteers = new HashSet<PlayVolunteer>();
            this.CourseAttendances = new HashSet<CourseAttendance>();
        }
    
        public int PlayId { get; set; }
        public int StudentId { get; set; }
        public string Title { get; set; }
        public Nullable<int> ProductionId { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual ICollection<PlayVolunteer> PlayVolunteers { get; set; }
        public virtual ICollection<CourseAttendance> CourseAttendances { get; set; }
        public virtual Production Production { get; set; }
    }
}
