//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SceneCrm.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Production
    {
        public Production()
        {
            this.Performances = new HashSet<Performance>();
            this.ProductionVolunteers = new HashSet<ProductionVolunteer>();
            this.Plays = new HashSet<Play>();
        }
    
        public int ProductionId { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<Performance> Performances { get; set; }
        public virtual ICollection<ProductionVolunteer> ProductionVolunteers { get; set; }
        public virtual ICollection<Play> Plays { get; set; }
    }
}
