//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SceneCrm.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentHistory
    {
        public int StudentId { get; set; }
        public string MembershipNumber { get; set; }
        public string StudentForename { get; set; }
        public string StudentSurname { get; set; }
        public string CourseTypeName { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<bool> Completed { get; set; }
        public string PlayTitle { get; set; }
        public string ProductionTitle { get; set; }
    }
}
