//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SceneCrm.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.CourseAttendances = new HashSet<CourseAttendance>();
            this.Plays = new HashSet<Play>();
        }
    
        public int StudentId { get; set; }
        public string MembershipNumber { get; set; }
        public string Forename { get; set; }
        public string Surname { get; set; }
        public string QuestionnaireResponse { get; set; }
    
        public virtual ICollection<CourseAttendance> CourseAttendances { get; set; }
        public virtual ICollection<Play> Plays { get; set; }
    }
}
