//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SceneCrm.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VolunteerHistory
    {
        public int volunteerid { get; set; }
        public string firstname { get; set; }
        public string surname { get; set; }
        public string type { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string notes { get; set; }
        public Nullable<int> playid { get; set; }
        public Nullable<int> courseid { get; set; }
        public Nullable<int> productionid { get; set; }
    }
}
